import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

import { IonicModule } from '@ionic/angular';

import { DashboardMemberPageRoutingModule } from './dashboard-member-routing.module';

import { DashboardMemberPage } from './dashboard-member.page';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    DashboardMemberPageRoutingModule
  ],
  declarations: [DashboardMemberPage]
})
export class DashboardMemberPageModule {}
