import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

import { IonicModule } from '@ionic/angular';

import { ManageSellerPageRoutingModule } from './manage-seller-routing.module';

import { ManageSellerPage } from './manage-seller.page';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    ManageSellerPageRoutingModule
  ],
  declarations: [ManageSellerPage]
})
export class ManageSellerPageModule {}
