import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

import { IonicModule } from '@ionic/angular';

import { DashboardStorePageRoutingModule } from './dashboard-store-routing.module';

import { DashboardStorePage } from './dashboard-store.page';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    DashboardStorePageRoutingModule
  ],
  declarations: [DashboardStorePage]
})
export class DashboardStorePageModule {}
