import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

import { IonicModule } from '@ionic/angular';

import { LoginStorePageRoutingModule } from './login-store-routing.module';

import { LoginStorePage } from './login-store.page';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    LoginStorePageRoutingModule
  ],
  declarations: [LoginStorePage]
})
export class LoginStorePageModule {}
