import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

import { IonicModule } from '@ionic/angular';

import { ManageCategoryPageRoutingModule } from './manage-category-routing.module';

import { ManageCategoryPage } from './manage-category.page';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    ManageCategoryPageRoutingModule
  ],
  declarations: [ManageCategoryPage]
})
export class ManageCategoryPageModule {}
